### ISSUE TITLE
Build erro

### ISSUE THREAD

**Issue by thomas-tran** [uport-project/veramo#515] opened 2021-05-14 06:26 UTC
**Bug severity**
5

**Describe the bug**
Unable to build

**To Reproduce**
Steps to reproduce the behaviour:
1. yarn install
2. yarn build
3. ...
4. ...

**Observed behaviour**
Build error
$ thomastran/veramo/node_modules/.bin/veramo dev extract-api
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run extract-api stderr:
/usr/bin/env: ‘node\r’: No such file or directory
error Command failed with exit code 127.
error Command failed with exit code 127.
lerna ERR! yarn run extract-api exited 127 in '@veramo/did-manager'
lerna WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
   
**Expected behaviour**
Build successfully

**Details**
If applicable, add screenshots, error messages or stack traces to help explain your problem.

**Additional context**

**Versions (please complete the following information):**
 - Veramo: current
 - Node Version 14.17.0

**Comment by jasonhealy** [comment] 2021-05-14 10:46
Hi @thomas-tran,

Did you run `yarn bootstrap` before building ?

**Comment by thomas-tran** [comment] 2021-05-14 10:51
yarn install
yarn bootstrap
yarn build

and still got erro

**Comment by jasonhealy** [comment] 2021-05-14 11:00
Is there any chance your Node installation is broken? Building fine on my end and in our CI https://github.com/uport-project/veramo/runs/2554783199?check_suite_focus=true

**Comment by thomas-tran** [comment] 2021-05-14 11:14
I've re-cloned the latest version, downgrade the node js from version 15 to 12.20.0 and run the following on ubuntu 20.08

yarn install
yarn bootstrap
yarn build


lerna notice cli v4.0.0
lerna info Executing command in 14 packages: "yarn run extract-api"
lerna ERR! yarn run extract-api exited 127 in '@veramo/did-manager'
lerna ERR! yarn run extract-api stdout:
$ yarn veramo dev extract-api
$ /mnt/d/Works/agent/veramo/node_modules/.bin/veramo dev extract-api
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run extract-api stderr:
/usr/bin/env: ‘node\r’: No such file or directory
error Command failed with exit code 127.
error Command failed with exit code 127.
lerna ERR! yarn run extract-api exited 127 in '@veramo/did-manager'
lerna WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by jasonhealy** [comment] 2021-05-14 11:19
`/usr/bin/env: ‘node\r’: No such file or directory` This indicates to me it could be an issue with your Node path?

**Comment by thomas-tran** [comment] 2021-05-14 12:26
/usr/bin/env: ‘node\r’: No such file or directory look like some commit with the windows style 'node\r’.  I tried to find why it failed.

Anyway, I switch to windows machine and it was ok however I got those warning 

![image](https://user-images.githubusercontent.com/5725085/118270435-693bfb00-b503-11eb-91b8-656825ad87e1.png)

**Comment by mirceanis** [comment] 2021-05-17 14:22
@thomas-tran, the warnings are to be expected.
This repo will try to use the latest of both typescript and api extractor, and since the latter takes a while to release, it's expected that it will be a few versions behind typescript.

Is the original issue still manifesting? If yes, please try clearing caches and removing `node_modules`
```bash
yarn cache clean --all
rm -rf node_modules
yarn install
yarn bootstrap
yarn build
```
If the issue is no longer manifesting, please close it.
Thank you for your contribution!

**Closed** 2021-07-24 00:51 UTC
Labels: bug, wontfix
